'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.WSReniecSoap")>  _
    Public Interface WSReniecSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Buscar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Buscar(ByVal Ingrese_dni As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Buscar", ReplyAction:="*")>  _
        Function BuscarAsync(ByVal Ingrese_dni As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WSReniecSoapChannel
        Inherits ServiceReference1.WSReniecSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WSReniecSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.WSReniecSoap)
        Implements ServiceReference1.WSReniecSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Buscar(ByVal Ingrese_dni As String) As System.Data.DataSet Implements ServiceReference1.WSReniecSoap.Buscar
            Return MyBase.Channel.Buscar(Ingrese_dni)
        End Function
        
        Public Function BuscarAsync(ByVal Ingrese_dni As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServiceReference1.WSReniecSoap.BuscarAsync
            Return MyBase.Channel.BuscarAsync(Ingrese_dni)
        End Function
    End Class
End Namespace
